### ISSUE TITLE
How to style popover ? 

### ISSUE THREAD

**Issue by Rohanhacker** [yesmeck/styled-antd#1]
This works fine for button and most component but not with popover as it doesn't allow className prop 

https://github.com/ant-design/ant-design/issues/11364

**Comment by yesmeck** [comment]
`Popover` need to be wrapped to support `styled-component`:


```javascript
const MyPopover = ({ className, ...props }) => <Popover {...props} overlayClassName={className} />
```

**Comment by Rohanhacker** [comment]
thanks make sense

**Comment by kocendavid** [comment]
Popover doesn't have such a prop. You have to use global style. AntD Popover component only represents the button the actual popover.  Not sure how to style multiple popovers tho

**Comment by prkagrawal** [comment]
> `Popover` need to be wrapped to support `styled-component`:
> 
> ```js
> const MyPopover = ({ className, ...props }) => <Popover {...props} overlayClassName={className} />
> ```

Why do we need to do this?

**Comment by yesmeck** [comment]
Popover doesn't have className prop which required by styled-component.
